// packages/implementations/react/src/atomic/Title/src/Title.tsx
import React from "react";
import { title } from "@rarui/styles";

import { TitleProps } from "./title.types";

const Title: React.FC<TitleProps> = ({
  className: _className,
  style: _style,
  as: As = "h1",
  textAlign = "left",
  fontWeight = "$bold",
  children,
  ...rest
}) => {
  const { className, style, otherProps } = title.sprinkle({
    ...(rest as Parameters<typeof title.sprinkle>[0]),
    textAlign,
    fontWeight,
  });

  return (
    <As
      className={[className, title.classnames.title({ as: As })].join(" ")}
      style={style}
      {...otherProps}
    >
      {children}
    </As>
  );
};

Title.displayName = "Title";

export { Title };

// packages/implementations/web-components/src/exhibition/Title/src/Title.tsx
import { Component, Prop, Element, h } from "@stencil/core";
import { title, CaptureCssProperties } from "@rarui/styles";

@Component({
  tag: "rarui-title",
})
export class RaruiTitle {
  private props: { [key: string]: any } = {};

  @Element() el: HTMLUListElement;
  @Prop() lineclamp: string;
  @Prop() as: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" = "h1";
  @CaptureCssProperties
  render() {
    const As = this.as;
    const { className, style, otherProps } = title.sprinkle({
      ...this.props,
      fontWeight: this.props.fontWeight ?? "$bold",
      textAlign: this.props.textAlign ?? "left",
    });

    return (
      <As
        class={[
          className,
          title.classnames.title({
            as: this.as,
          }),
        ].join(" ")}
        style={{ ...style, WebkitLineClamp: this?.lineclamp }}
        {...otherProps}
      >
        <slot></slot>
      </As>
    );
  }
}
