// packages/implementations/react/src/atomic/Badge/src/Badge.tsx
import React from "react";
import { badge } from "@rarui/styles";
import { BadgeProps } from "./badge.types";

const Badge: React.FC<BadgeProps> = ({
  className: _className,
  style: _style,
  appearance = "brand",
  size = "medium",
  variant = "solid",
  children,
  ...props
}) => (
  <div
    {...props}
    className={badge.classnames.badge({ appearance, variant, size })}
  >
    {size !== "dot" && children}
  </div>
);

Badge.displayName = "Badge";

export { Badge };

// packages/implementations/vuejs/src/atomic/Badge/src/Badge.vue
<template>
  <div :class="badge.classnames.badge({ appearance, size, variant })">
    <slot v-if="props.size != 'dot'" />
  </div>
</template>

<script lang="ts" setup>
import { badge } from "@rarui/styles";
import { BadgeProps } from "./badge.types";

const props = withDefaults(defineProps<BadgeProps>(), {
  appearance: "brand",
  size: "medium",
  variant: "solid",
});
</script>
