// packages/implementations/web-components/src/input/Button/src/Button.tsx
import { Component, Prop, Element, h } from "@stencil/core";
import { button, ButtonVariants } from "@rarui/styles";

@Component({
  tag: "rarui-button",
  scoped: true,
})
export class RaruiButton {
  @Element() el: HTMLButtonElement;

  @Prop() appearance: ButtonVariants["appearance"] = "brand";
  @Prop() variant: ButtonVariants["variant"] = "solid";
  @Prop() size: ButtonVariants["size"] = "large";
  @Prop() full: ButtonVariants["full"];
  @Prop() disabled: HTMLButtonElement["disabled"];
  @Prop() type: HTMLButtonElement["type"];
  @Prop() href: HTMLAnchorElement["href"];
  @Prop() target: HTMLAnchorElement["target"];
  @Prop() as: string = "button";

  render() {
    const As = this.as;
    return (
      <As
        class={button.classnames.button({
          appearance: this.appearance,
          variant: this.variant,
          size: this.size,
          full: this.full,
        })}
        disabled={this.disabled}
        type={this.type}
        href={this.href}
        target={this.target}
      >
        <slot></slot>
      </As>
    );
  }
}

// packages/implementations/react/src/input/Button/src/Button.tsx
import React, {
  ComponentPropsWithRef,
  forwardRef,
  useRef,
  useEffect,
  useImperativeHandle,
} from "react";
import { button } from "@rarui/styles";

import {
  PolymorphicForwardRefComponent,
  useRefObjectAsForwardedRef,
} from "../../../types";
import { _ButtonProps } from "./button.types";

const Button = forwardRef(
  (
    {
      className: _className,
      style: _style,
      as: As = "button",
      appearance = "brand",
      size = "large",
      variant = "solid",
      full,
      children,
      ...props
    }: _ButtonProps & { as: any },
    ref,
  ) => {
    const innerRef = useRef<HTMLButtonElement>(null);
    useRefObjectAsForwardedRef(ref, innerRef);

    useImperativeHandle<
      HTMLButtonElement | HTMLAnchorElement | null,
      HTMLButtonElement | null
    >(ref, () => innerRef?.current);

    useEffect(() => {
      if (
        innerRef.current &&
        !(innerRef.current instanceof HTMLAnchorElement) &&
        !(innerRef.current instanceof HTMLButtonElement)
      ) {
        console.error(
          "Error: Found `Button` component that renders an inaccessible element",
          innerRef.current,
          "Please ensure `Button` always renders as <a> or <button>",
        );
      }
    }, [innerRef]);

    return (
      <As
        {...props}
        className={button.classnames.button({
          size,
          variant,
          appearance,
          full,
        })}
        ref={innerRef}
      >
        {children}
      </As>
    );
  },
) as PolymorphicForwardRefComponent<"button" | "a", _ButtonProps>;

Button.displayName = "Button";

export type ButtonProps = ComponentPropsWithRef<typeof Button>;
export { Button };
