// packages/implementations/web-components/src/exhibition/Text/src/Text.tsx
import { Component, Prop, Element, h } from "@stencil/core";
import { text, CaptureCssProperties } from "@rarui/styles";

@Component({
  tag: "rarui-text",
})
export class RaruiText {
  private props: { [key: string]: any } = {};

  @Element() el: HTMLUListElement;
  @Prop() lineClamp: string;
  @Prop() as: "p" | "span" = "p";
  @CaptureCssProperties
  render() {
    const As = this.as;
    const { className, style, otherProps } = text.sprinkle({
      ...this.props,
      fontWeight: this.props.fontWeight ?? "$regular",
    });

    return (
      <As
        class={[
          className,
          text.classnames.text({
            lineClamp: !!this?.lineClamp,
          }),
        ].join(" ")}
        style={{ ...style, WebkitLineClamp: this?.lineClamp }}
        {...otherProps}
      >
        <slot></slot>
      </As>
    );
  }
}

// packages/implementations/react/src/atomic/Text/src/Text.tsx
import React from "react";
import { text } from "@rarui/styles";

import { TextProps } from "./text.types";

const Text: React.FC<TextProps> = ({
  className: _className,
  style: _style,
  as: As = "p",
  textAlign = "left",
  fontWeight = "$regular",
  children,
  lineClamp,
  ...rest
}) => {
  const { className, style, otherProps } = text.sprinkle({
    ...(rest as Parameters<typeof text.sprinkle>[0]),
    textAlign,
    fontWeight,
  });

  return (
    <As
      className={[
        className,
        text.classnames.text({ lineClamp: !!lineClamp }),
      ].join(" ")}
      style={{ ...style, WebkitLineClamp: lineClamp }}
      {...otherProps}
    >
      {children}
    </As>
  );
};

Text.displayName = "Text";

export { Text };
