// packages/implementations/react/src/atomic/Chip/src/Chip.tsx
import React from "react";
import { chip } from "@rarui/styles";

import { ChipProps } from "./chip.types";

const Chip: React.FC<ChipProps> = ({
  className: _className,
  style: _style,
  pill = false,
  closeable = false,
  selected,
  avatar,
  children,
  ...props
}) => {
  return (
    <div {...props} className={chip.classnames.chip({ pill, selected })}>
      {avatar && <div>{avatar}</div>}
      {children}
      {closeable && <div>x</div>}

      <span className={chip.classnames.overlay} />
    </div>
  );
};
Chip.displayName = "Chip";

export { Chip };

// packages/implementations/vuejs/src/atomic/Chip/src/Chip.vue
<template>
  <component
    :is="closeable || disabled ? 'button' : 'div'"
    :class="chip.classnames.chip({ pill, selected })"
    :disabled="disabled"
  >
    <slot v-if="avatar" name="avatar">
      <!-- fazer avatar -->
    </slot>
    <slot />
    <slot v-if="closeable" name="closeable">
      <!-- fazer icone -->
    </slot>
    <span :class="chip.classnames.overlay" />
  </component>
</template>

<script lang="ts" setup>
import { chip } from "@rarui/styles";
import { ChipProps } from "./chip.types";

defineOptions({
  inheritAttrs: false,
});

withDefaults(defineProps<ChipProps>(), {
  pill: false,
  disabled: false,
  closeable: false,
  avatar: "",
});
</script>
